matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install mypy
      script:
        - ./python_tests.sh
    - language: node_js
      node_js:
        - 12
      before_script:
        - yarn install
      script:
        - yarn type-check
